//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webService.DaoEtud {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interface/", ConfigurationName="DaoEtud.IDAOEtudiant")]
    public interface IDAOEtudiant {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEtudiant/findByRequest", ReplyAction="http://Interface/IDAOEtudiant/findByResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEtudResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEtud))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findByResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBy))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webService.DaoEtud.findByResponse1 findBy(webService.DaoEtud.findByRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEtudiant/findByRequest", ReplyAction="http://Interface/IDAOEtudiant/findByResponse")]
        System.Threading.Tasks.Task<webService.DaoEtud.findByResponse1> findByAsync(webService.DaoEtud.findByRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEtudiant/insertEtudRequest", ReplyAction="http://Interface/IDAOEtudiant/insertEtudResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEtudResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEtud))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findByResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBy))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webService.DaoEtud.insertEtudResponse1 insertEtud(webService.DaoEtud.insertEtudRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEtudiant/insertEtudRequest", ReplyAction="http://Interface/IDAOEtudiant/insertEtudResponse")]
        System.Threading.Tasks.Task<webService.DaoEtud.insertEtudResponse1> insertEtudAsync(webService.DaoEtud.insertEtudRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class insertEtudResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class insertEtud : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
                this.RaisePropertyChanged("arg2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class findByResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class findBy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBy", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class findByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object arg0;
        
        public findByRequest() {
        }
        
        public findByRequest(object arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByResponse", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class findByResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object @return;
        
        public findByResponse1() {
        }
        
        public findByResponse1(object @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertEtud", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class insertEtudRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public insertEtudRequest() {
        }
        
        public insertEtudRequest(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertEtudResponse", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class insertEtudResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertEtudResponse1() {
        }
        
        public insertEtudResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDAOEtudiantChannel : webService.DaoEtud.IDAOEtudiant, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DAOEtudiantClient : System.ServiceModel.ClientBase<webService.DaoEtud.IDAOEtudiant>, webService.DaoEtud.IDAOEtudiant {
        
        public DAOEtudiantClient() {
        }
        
        public DAOEtudiantClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DAOEtudiantClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DAOEtudiantClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DAOEtudiantClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webService.DaoEtud.findByResponse1 webService.DaoEtud.IDAOEtudiant.findBy(webService.DaoEtud.findByRequest request) {
            return base.Channel.findBy(request);
        }
        
        public object findBy(object arg0) {
            webService.DaoEtud.findByRequest inValue = new webService.DaoEtud.findByRequest();
            inValue.arg0 = arg0;
            webService.DaoEtud.findByResponse1 retVal = ((webService.DaoEtud.IDAOEtudiant)(this)).findBy(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webService.DaoEtud.findByResponse1> webService.DaoEtud.IDAOEtudiant.findByAsync(webService.DaoEtud.findByRequest request) {
            return base.Channel.findByAsync(request);
        }
        
        public System.Threading.Tasks.Task<webService.DaoEtud.findByResponse1> findByAsync(object arg0) {
            webService.DaoEtud.findByRequest inValue = new webService.DaoEtud.findByRequest();
            inValue.arg0 = arg0;
            return ((webService.DaoEtud.IDAOEtudiant)(this)).findByAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webService.DaoEtud.insertEtudResponse1 webService.DaoEtud.IDAOEtudiant.insertEtud(webService.DaoEtud.insertEtudRequest request) {
            return base.Channel.insertEtud(request);
        }
        
        public bool insertEtud(string arg0, string arg1, string arg2) {
            webService.DaoEtud.insertEtudRequest inValue = new webService.DaoEtud.insertEtudRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            webService.DaoEtud.insertEtudResponse1 retVal = ((webService.DaoEtud.IDAOEtudiant)(this)).insertEtud(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webService.DaoEtud.insertEtudResponse1> webService.DaoEtud.IDAOEtudiant.insertEtudAsync(webService.DaoEtud.insertEtudRequest request) {
            return base.Channel.insertEtudAsync(request);
        }
        
        public System.Threading.Tasks.Task<webService.DaoEtud.insertEtudResponse1> insertEtudAsync(string arg0, string arg1, string arg2) {
            webService.DaoEtud.insertEtudRequest inValue = new webService.DaoEtud.insertEtudRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((webService.DaoEtud.IDAOEtudiant)(this)).insertEtudAsync(inValue);
        }
    }
}
