//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webService.DaoEmp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Interface/", ConfigurationName="DaoEmp.IDAOEmpreint")]
    public interface IDAOEmpreint {
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEmpreint/findByRequest", ReplyAction="http://Interface/IDAOEmpreint/findByResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findByResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEmResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEm))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webService.DaoEmp.findByResponse1 findBy(webService.DaoEmp.findByRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEmpreint/findByRequest", ReplyAction="http://Interface/IDAOEmpreint/findByResponse")]
        System.Threading.Tasks.Task<webService.DaoEmp.findByResponse1> findByAsync(webService.DaoEmp.findByRequest request);
        
        // CODEGEN : Le paramètre 'return' nécessite des informations de schéma supplémentaires qui ne peuvent pas être capturées en utilisant le mode du paramètre. L'attribut spécifique est 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEmpreint/insertEmRequest", ReplyAction="http://Interface/IDAOEmpreint/insertEmResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findByResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findBy))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEmResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(insertEm))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        webService.DaoEmp.insertEmResponse1 insertEm(webService.DaoEmp.insertEmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Interface/IDAOEmpreint/insertEmRequest", ReplyAction="http://Interface/IDAOEmpreint/insertEmResponse")]
        System.Threading.Tasks.Task<webService.DaoEmp.insertEmResponse1> insertEmAsync(webService.DaoEmp.insertEmRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class findByResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class findBy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class insertEmResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Interface/")]
    public partial class insertEm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string arg0Field;
        
        private string arg1Field;
        
        private string arg2Field;
        
        private string arg3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string arg1 {
            get {
                return this.arg1Field;
            }
            set {
                this.arg1Field = value;
                this.RaisePropertyChanged("arg1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string arg2 {
            get {
                return this.arg2Field;
            }
            set {
                this.arg2Field = value;
                this.RaisePropertyChanged("arg2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string arg3 {
            get {
                return this.arg3Field;
            }
            set {
                this.arg3Field = value;
                this.RaisePropertyChanged("arg3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findBy", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class findByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object arg0;
        
        public findByRequest() {
        }
        
        public findByRequest(object arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findByResponse", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class findByResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object @return;
        
        public findByResponse1() {
        }
        
        public findByResponse1(object @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertEm", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class insertEmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        public insertEmRequest() {
        }
        
        public insertEmRequest(string arg0, string arg1, string arg2, string arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertEmResponse", WrapperNamespace="http://Interface/", IsWrapped=true)]
    public partial class insertEmResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Interface/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public insertEmResponse1() {
        }
        
        public insertEmResponse1(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDAOEmpreintChannel : webService.DaoEmp.IDAOEmpreint, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DAOEmpreintClient : System.ServiceModel.ClientBase<webService.DaoEmp.IDAOEmpreint>, webService.DaoEmp.IDAOEmpreint {
        
        public DAOEmpreintClient() {
        }
        
        public DAOEmpreintClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DAOEmpreintClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DAOEmpreintClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DAOEmpreintClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webService.DaoEmp.findByResponse1 webService.DaoEmp.IDAOEmpreint.findBy(webService.DaoEmp.findByRequest request) {
            return base.Channel.findBy(request);
        }
        
        public object findBy(object arg0) {
            webService.DaoEmp.findByRequest inValue = new webService.DaoEmp.findByRequest();
            inValue.arg0 = arg0;
            webService.DaoEmp.findByResponse1 retVal = ((webService.DaoEmp.IDAOEmpreint)(this)).findBy(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webService.DaoEmp.findByResponse1> webService.DaoEmp.IDAOEmpreint.findByAsync(webService.DaoEmp.findByRequest request) {
            return base.Channel.findByAsync(request);
        }
        
        public System.Threading.Tasks.Task<webService.DaoEmp.findByResponse1> findByAsync(object arg0) {
            webService.DaoEmp.findByRequest inValue = new webService.DaoEmp.findByRequest();
            inValue.arg0 = arg0;
            return ((webService.DaoEmp.IDAOEmpreint)(this)).findByAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webService.DaoEmp.insertEmResponse1 webService.DaoEmp.IDAOEmpreint.insertEm(webService.DaoEmp.insertEmRequest request) {
            return base.Channel.insertEm(request);
        }
        
        public bool insertEm(string arg0, string arg1, string arg2, string arg3) {
            webService.DaoEmp.insertEmRequest inValue = new webService.DaoEmp.insertEmRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            webService.DaoEmp.insertEmResponse1 retVal = ((webService.DaoEmp.IDAOEmpreint)(this)).insertEm(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webService.DaoEmp.insertEmResponse1> webService.DaoEmp.IDAOEmpreint.insertEmAsync(webService.DaoEmp.insertEmRequest request) {
            return base.Channel.insertEmAsync(request);
        }
        
        public System.Threading.Tasks.Task<webService.DaoEmp.insertEmResponse1> insertEmAsync(string arg0, string arg1, string arg2, string arg3) {
            webService.DaoEmp.insertEmRequest inValue = new webService.DaoEmp.insertEmRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            return ((webService.DaoEmp.IDAOEmpreint)(this)).insertEmAsync(inValue);
        }
    }
}
